// The Content-Security-Policy of the app page (CD-92), built from the same variables the bundle is
// built with, so it names the exact Sentry host instead of a wildcard.
//
//   node scripts/csp.mjs policy   # the policy, one line (e.g. CSP_PREVIEW for `vite preview`)
//   node scripts/csp.mjs nginx    # an nginx include with the header (the Docker image uses this)
//
// CSP_ENFORCE=true sends Content-Security-Policy; otherwise Content-Security-Policy-Report-Only,
// which only reports. Reports go to the frontend's Sentry project when VITE_SENTRY_DSN is set.

const env = process.env;

function sentry() {
  try {
    const dsn = env.VITE_SENTRY_DSN ? new URL(env.VITE_SENTRY_DSN) : null;
    if (!dsn) return null;
    const host = `${dsn.protocol}//${dsn.host}`;
    const project = dsn.pathname.replace(/^\/+/, '');
    return { host, report: project && dsn.username ? `${host}/api/${project}/security/?sentry_key=${dsn.username}` : null };
  } catch {
    return null;
  }
}

export function policy() {
  const s = sentry();
  const directives = [
    ["default-src", "'self'"],
    // Cloudflare Web Analytics: Cloudflare adds its beacon script to the page and it reports to
    // cloudflareinsights.com (Sentry CRM-FRONTEND-1).
    ["script-src", "'self' https://static.cloudflareinsights.com"],
    // 'unsafe-inline' for style attributes: React renders inline styles throughout the app.
    ["style-src", "'self' 'unsafe-inline' https://fonts.googleapis.com"],
    ["font-src", "'self' https://fonts.gstatic.com"],
    ["img-src", "'self' data: blob:"],
    // The API is same-origin, sign-in included (CD-114: the backend talks to the provider); Sentry;
    // Cloudflare Web Analytics.
    ["connect-src", ["'self'", s?.host, 'https://cloudflareinsights.com'].filter(Boolean).join(' ')],
    // The live-update worker is a bundled file.
    ["worker-src", "'self'"],
    ["frame-src", "'none'"],
    ["frame-ancestors", "'none'"],
    ["object-src", "'none'"],
    ["base-uri", "'self'"],
    ["form-action", "'self'"],
  ];
  if (s?.report) directives.push(['report-uri', s.report]);
  return directives.map(([k, v]) => `${k} ${v}`).join('; ');
}

export function nginxInclude() {
  const header = env.CSP_ENFORCE === 'true' ? 'Content-Security-Policy' : 'Content-Security-Policy-Report-Only';
  return `# Generated by scripts/csp.mjs at image build time (CD-92).\nadd_header ${header} "${policy()}" always;\n`;
}

if (process.argv[1]?.endsWith('csp.mjs')) {
  const what = process.argv[2];
  if (what === 'policy') process.stdout.write(`${policy()}\n`);
  else if (what === 'nginx') process.stdout.write(nginxInclude());
  else {
    process.stderr.write('usage: node scripts/csp.mjs policy|nginx\n');
    process.exit(2);
  }
}
