// Site copy in English and Serbian (Latin script), from the Claude Design handoff "Pultly Website".
// Serbian must have exactly the same keys as English; TypeScript checks it.
const en = {
  langLabel: 'Language', navProduct: 'Product', navModules: 'Modules', navBlog: 'Blog', signIn: 'Sign in', tryCta: 'Try Pultly',
  eyebrow: 'One pult for the whole business', h1: 'One pult for',
  words: ['sales.', 'planning.', 'projects.', 'people.', 'reporting.'],
  heroSub: 'Pultly is one workspace for small and mid-sized businesses. It starts with CRM: your funnel, your day and the whole picture on one screen. Planning, projects, workforce and reporting follow.',createAccount: 'Create account',
  mockNav: ['Overview', 'Pipeline', 'Today', 'Companies', 'Contacts', 'Settings'],
  mockTitle: 'Overview', mockSearch: 'Search deals, companies…',
  stats: ['Open pipeline', 'Won this month', 'Due today', 'Stalled deals'],
  statNotes: ['14 deals in the funnel', '+3 deals', '2 overdue', 'No activity for 7+ days'],
  mockFunnel: 'Pipeline funnel', mockFunnelSub: 'Deals and value by stage',
  funnel: [{ name: 'Lead', meta: '14 · €412k' }, { name: 'Discovery', meta: '9 · €268k' }, { name: 'Proposal', meta: '5 · €154k' }, { name: 'Negotiation', meta: '3 · €97k' }, { name: 'Won', meta: '2 · €86k' }],
  funnelShort: [{ name: 'Lead', meta: '14' }, { name: 'Discovery', meta: '9' }, { name: 'Proposal', meta: '5' }, { name: 'Won', meta: '2' }],
  mockStalled: 'Stalled deals', mockStalledSub: 'Open deals with no activity for a week',
  stalled: [{ ini: 'NW', name: 'Northwind website redesign', meta: 'Northwind · Proposal · Ana Petrović', days: '12 d' }, { ini: 'BS', name: 'Brand refresh', meta: 'Brankov studio · Discovery · Marko Ilić', days: '9 d' }, { ini: 'AL', name: 'Fleet dashboard', meta: 'Adria Logistics · Negotiation · Ana Petrović', days: '8 d' }, { ini: 'KV', name: 'Annual retainer', meta: 'Kvadrat · Proposal · Jelena Rakić', days: '7 d' }],
  howCaps: 'How it works', howTitle: 'From first contact to signed deal, in one place.',
  s1t: 'Add a deal', s1d: 'Enter a deal or import a CSV file. Deals move through your funnel\'s stages, left to right.',
  stages: ['Lead', 'Discovery', 'Proposal', 'Won'], dealName: 'Northwind website redesign', dealMeta: 'Northwind · €24k · Ana Petrović',
  s2t: 'Today fills itself', s2d: 'Each deal brings its next step, plus the tasks you add. In the morning you see what is due.',
  tasks: [{ title: 'Send proposal to Northwind', meta: 'Northwind · Proposal · due today' }, { title: 'Call Marko about the brief', meta: 'Brankov studio · Discovery · due today' }, { title: 'Book kickoff with Adria', meta: 'Adria Logistics · Negotiation · tomorrow' }],
  s3t: 'The pult shows the whole picture', s3d: 'Open pipeline, the funnel and stalled deals on one screen, built from the deals you already track.',
  toolsCaps: 'Instead of five tools', toolsTitle: 'Fewer browser tabs.',
  toolsBody: 'A spreadsheet for sales, an app for tasks, another for time, Excel for reports. Pultly puts them in one workspace, so the same data is never copied twice.',
  tools: [{ a: 'Sales spreadsheet', b: 'Pipeline' }, { a: 'To-do app', b: 'Today' }, { a: 'Contacts in your phone', b: 'Companies' }, { a: 'Monthly report in Excel', b: 'Overview' }],
  modCaps: 'Modules', modTitle: 'CRM today. The rest of the pult next.',
  modBody: 'Every module shares the same companies, people and deals. CRM is available now; the others arrive one by one.',
  live: 'Available', soon: 'Coming soon',
  mods: [['Sales', 'Funnel, companies, contacts and deals with a fit score. Every deal has a next step.'], ['Planning', 'Monthly goals and plans, next to what actually happens in sales.'], ['Projects', 'A won deal becomes a project with tasks, deadlines and people.'], ['Workforce', 'Who is on what, who is free and how loaded the team is.'], ['Reporting', 'Reports built from the data you already enter.']],
  forCaps: 'Who it\'s for', forTitle: 'Built for small teams with a lot going on.',
  audiences: [{ icon: 'team', t: 'Agencies', d: 'Follow each client from proposal to signed deal without retyping anything.' }, { icon: 'building', t: 'Studios', d: 'A small team and many deals. Everyone sees what happens next.' }, { icon: 'location', t: 'Growing businesses', d: 'Start with sales today. Add planning, projects and your team as you grow, without switching tools.' }],
  blogTeaser: 'From the blog', allArticles: 'All articles', read: 'Read article',
  nlTitle: 'One email a month, worth reading.', nlSub: 'Guides on sales, planning and running a small business, plus what is new in Pultly.', nlPlaceholder: 'Your email', nlCta: 'Subscribe', nlNote: 'No spam. Unsubscribe with one click.', nlDone: 'Thanks! You are on the list.', nlError: 'That didn\'t work. Please try again.',
  blogTitle: 'Blog', blogSub: 'Guides on sales, planning and running a small business, plus news from Pultly.',
  cats: { all: 'All', guides: 'Guides', sales: 'Sales', product: 'Product' }, minRead: 'min read', by: 'Pultly team',
  moreArticles: 'More articles',
  footTag: 'One workspace for planning, CRM, projects, workforce and reporting.', footProduct: 'Product', footAccount: 'Account'
};

export type Copy = typeof en;
const sr: Copy = {
  langLabel: 'Jezik', navProduct: 'Proizvod', navModules: 'Moduli', navBlog: 'Blog', signIn: 'Prijava', tryCta: 'Isprobajte Pultly',
  eyebrow: 'Jedan pult za ceo biznis', h1: 'Jedan pult za',
  words: ['prodaju.', 'planiranje.', 'projekte.', 'ljude.', 'izveštaje.'],
  heroSub: 'Pultly je jedan radni prostor za male i srednje firme. Počinje od CRM-a: vaš levak, vaš dan i cela slika na jednom ekranu. Slede planiranje, projekti, tim i izveštaji.',createAccount: 'Napravite nalog',
  mockNav: ['Pregled', 'Levak', 'Danas', 'Firme', 'Kontakti', 'Podešav.'],
  mockTitle: 'Pregled', mockSearch: 'Pretražite poslove, firme…',
  stats: ['Otvoreni levak', 'Dobijeno ovog meseca', 'Za danas', 'Zastali poslovi'],
  statNotes: ['14 poslova u levku', '+3 posla', '2 kasne', 'Bez aktivnosti 7+ dana'],
  mockFunnel: 'Prodajni levak', mockFunnelSub: 'Poslovi i vrednost po fazi',
  funnel: [{ name: 'Lead', meta: '14 · €412k' }, { name: 'Discovery', meta: '9 · €268k' }, { name: 'Ponuda', meta: '5 · €154k' }, { name: 'Pregovori', meta: '3 · €97k' }, { name: 'Dobijeno', meta: '2 · €86k' }],
  funnelShort: [{ name: 'Lead', meta: '14' }, { name: 'Discovery', meta: '9' }, { name: 'Ponuda', meta: '5' }, { name: 'Dobijeno', meta: '2' }],
  mockStalled: 'Zastali poslovi', mockStalledSub: 'Otvoreni poslovi bez aktivnosti nedelju dana',
  stalled: [{ ini: 'NW', name: 'Redizajn sajta Northwind', meta: 'Northwind · Ponuda · Ana Petrović', days: '12 d' }, { ini: 'BS', name: 'Osveženje brenda', meta: 'Brankov studio · Discovery · Marko Ilić', days: '9 d' }, { ini: 'AL', name: 'Kontrolna tabla voznog parka', meta: 'Adria Logistics · Pregovori · Ana Petrović', days: '8 d' }, { ini: 'KV', name: 'Godišnji ugovor', meta: 'Kvadrat · Ponuda · Jelena Rakić', days: '7 d' }],
  howCaps: 'Kako radi', howTitle: 'Od prvog kontakta do potpisanog posla, na jednom mestu.',
  s1t: 'Dodajte posao', s1d: 'Unesite posao ili uvezite CSV fajl. Poslovi idu kroz faze vašeg levka, s leva na desno.',
  stages: ['Lead', 'Discovery', 'Ponuda', 'Dobijeno'], dealName: 'Redizajn sajta Northwind', dealMeta: 'Northwind · €24k · Ana Petrović',
  s2t: 'Danas se puni samo', s2d: 'Svaki posao donosi svoj sledeći korak, uz zadatke koje dodate. Ujutru vidite šta je na redu.',
  tasks: [{ title: 'Poslati ponudu za Northwind', meta: 'Northwind · Ponuda · danas' }, { title: 'Pozvati Marka oko brifa', meta: 'Brankov studio · Discovery · danas' }, { title: 'Zakazati početni sastanak sa Adrijom', meta: 'Adria Logistics · Pregovori · sutra' }],
  s3t: 'Pult pokazuje celu sliku', s3d: 'Otvoreni levak, faze i zastali poslovi na jednom ekranu, iz poslova koje već vodite.',
  toolsCaps: 'Umesto pet alata', toolsTitle: 'Manje otvorenih tabova.',
  toolsBody: 'Tabela za prodaju, aplikacija za zadatke, druga za vreme, Excel za izveštaje. Pultly ih spaja u jedan radni prostor, pa se isti podaci nikad ne kopiraju dvaput.',
  tools: [{ a: 'Tabela za prodaju', b: 'Levak' }, { a: 'To-do aplikacija', b: 'Danas' }, { a: 'Kontakti u telefonu', b: 'Firme' }, { a: 'Mesečni izveštaj u Excelu', b: 'Pregled' }],
  modCaps: 'Moduli', modTitle: 'Danas CRM. Ostatak pulta uskoro.',
  modBody: 'Svi moduli dele iste firme, ljude i poslove. CRM je dostupan sada, a ostali stižu jedan po jedan.',
  live: 'Dostupno', soon: 'Uskoro',
  mods: [['Prodaja', 'Levak, firme, kontakti i poslovi sa fit skorom. Svaki posao ima sledeći korak.'], ['Planiranje', 'Mesečni ciljevi i planovi, pored onoga što se stvarno dešava u prodaji.'], ['Projekti', 'Dobijen posao postaje projekat sa zadacima, rokovima i ljudima.'], ['Tim', 'Ko je na čemu, ko je slobodan i koliko je tim opterećen.'], ['Izveštaji', 'Izveštaji iz podataka koje već unosite.']],
  forCaps: 'Za koga je', forTitle: 'Za male timove sa puno posla.',
  audiences: [{ icon: 'team', t: 'Agencije', d: 'Pratite svakog klijenta od ponude do potpisanog posla, bez prepisivanja.' }, { icon: 'building', t: 'Studiji', d: 'Mali tim i mnogo poslova. Svi vide šta je sledeće.' }, { icon: 'location', t: 'Firme u rastu', d: 'Počnite od prodaje danas. Dodajte planiranje, projekte i tim kako rastete, bez menjanja alata.' }],
  blogTeaser: 'Sa bloga', allArticles: 'Svi članci', read: 'Pročitajte članak',
  nlTitle: 'Jedan mejl mesečno, vredan čitanja.', nlSub: 'Vodiči za prodaju, planiranje i vođenje male firme, i novosti iz Pultlyja.', nlPlaceholder: 'Vaš email', nlCta: 'Pretplatite se', nlNote: 'Bez spama. Odjava jednim klikom.', nlDone: 'Hvala! Na listi ste.', nlError: 'Nije uspelo. Pokušajte ponovo.',
  blogTitle: 'Blog', blogSub: 'Vodiči za prodaju, planiranje i vođenje male firme, i novosti iz Pultlyja.',
  cats: { all: 'Sve', guides: 'Vodiči', sales: 'Prodaja', product: 'Proizvod' }, minRead: 'min čitanja', by: 'Tim Pultly',
  moreArticles: 'Još članaka',
  footTag: 'Jedan radni prostor za planiranje, CRM, projekte, tim i izveštaje.', footProduct: 'Proizvod', footAccount: 'Nalog'
};

export type Lang = 'en' | 'sr';

export const COPY: Record<Lang, Copy> = { en, sr };
