import { useState } from 'react';
import { FilterBar } from '../components/ui';
import { Screen } from '../components/Layout';
import { CHANNEL_LABELS } from '../store/seed';
import { ownerOf, salesPeople, stageOf } from '../store/selectors';
import { useStore } from '../store/store';

/** "Today": tasks generated by the funnel — each lead's current stage activity. */
export function Today() {
  const { s, set, openLead } = useStore();
  const [query, setQuery] = useState('');
  const [owner, setOwner] = useState('Salesperson');

  const q = query.toLowerCase().trim();
  const tasks = s.leads
    .filter((l) => owner === 'Salesperson' || ownerOf(l) === owner)
    .map((l) => {
      const st = stageOf(s, l);
      return {
        id: l.id,
        title: st.activity,
        company: l.company,
        stageName: st.name,
        channelLabel: CHANNEL_LABELS[st.channel] || st.channel,
        due: l.stall >= 4 ? l.stall + ' days ago' : l.stall > 0 ? 'today' : 'tomorrow',
        bucket: l.stall >= 4 ? 0 : l.stall > 0 ? 1 : 2,
      };
    })
    .filter((t) => !q || t.company.toLowerCase().includes(q) || t.title.toLowerCase().includes(q));
  const groups = [
    { label: 'Overdue', fg: '#B42318', tasks: tasks.filter((t) => t.bucket === 0) },
    { label: 'Today', fg: '#101828', tasks: tasks.filter((t) => t.bucket === 1) },
    { label: 'Next up', fg: '#475467', tasks: tasks.filter((t) => t.bucket === 2) },
  ];

  return (
    <Screen title="Today">
      <FilterBar
        search={{ value: query, onChange: setQuery, placeholder: 'Search tasks' }}
        chips={[{ value: owner, options: ['Salesperson', ...salesPeople(s)], onChange: setOwner }]}
        dirty={owner !== 'Salesperson'}
        onClear={() => {
          setOwner('Salesperson');
          setQuery('');
        }}
        action={{ label: 'New task', onClick: () => set({ taskOpen: true }) }}
      />
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
        <div style={{ fontSize: 13.5, color: 'var(--text-2)', lineHeight: 1.55, maxWidth: 640 }}>Tasks are generated by the funnel, not written by hand. Each one opens with the script for that stage.</div>
        {groups.map((g) => (
          <div key={g.label} style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 9 }}>
              <span style={{ fontSize: 10.5, letterSpacing: '0.09em', textTransform: 'uppercase', color: g.fg }}>{g.label}</span>
              <span style={{ flex: 1, height: 1, background: 'var(--border)' }} />
              <span style={{ fontSize: 11, color: 'var(--text-2)' }}>{g.tasks.length} tasks</span>
            </div>
            {g.tasks.map((t) => (
              <div key={t.id} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 10, padding: '14px 15px', display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap' }}>
                <div style={{ flex: 1, minWidth: 200, display: 'flex', flexDirection: 'column', gap: 3 }}>
                  <span style={{ fontSize: 13.5, fontWeight: 600 }}>{t.title}</span>
                  <span style={{ fontSize: 12, color: 'var(--text-2)' }}>
                    {t.company} · {t.stageName} · due {t.due}
                  </span>
                </div>
                <span style={{ fontSize: 11.5, fontWeight: 500, background: 'var(--ink)', color: 'var(--white)', padding: '4px 9px', borderRadius: 6, whiteSpace: 'nowrap' }}>{t.channelLabel}</span>
                <button type="button" className="btn-outline" onClick={() => openLead(t.id)}>
                  Open script
                </button>
              </div>
            ))}
          </div>
        ))}
      </div>
    </Screen>
  );
}
