import { useState } from 'react';
import { FilterBar } from '../components/ui';
import { EmptyState } from '../components/EmptyState';
import { Screen } from '../components/Layout';
import { CHANNEL_LABELS } from '../store/seed';
import { isoLabel, isOverdue, leadById, memberName, salesPeople, stageOf, stagesFor, todayIso, todayLabel } from '../store/selectors';
import { useStore } from '../store/store';

interface TodayTask {
  id: string;
  leadId: string;
  title: string;
  company: string;
  stageName: string;
  channelLabel: string;
  due: string;
  bucket: number;
  /** Set for tasks added with "New task" (they can be ticked off and edited here). */
  task?: { done: boolean; owner: string; dueIso: string; overdue: boolean };
}

/**
 * "Today": tasks generated by the funnel (each lead's current stage activity) plus tasks added by
 * hand. Overdue (CD-67) holds the hand-added tasks that are past their due date and not done, by
 * the workspace's today (its time zone); the funnel's tasks have no due date, so they are never
 * overdue: a deal that has been quiet for a while sits under Today.
 */
export function Today() {
  const { s, set, openLead, toggleLeadTask } = useStore();
  const [owner, setOwner] = useState('Salesperson');

  const today = todayIso(s.workspace.timezone);
  const doneToday = todayLabel(s.workspace.timezone);
  const funnelTasks = s.leads
    .filter((l) => owner === 'Salesperson' || l.ownerId === owner)
    .map<TodayTask>((l) => {
      const st = stageOf(s, l);
      return {
        id: l.id,
        leadId: l.id,
        title: st.activity,
        company: l.company,
        stageName: st.name,
        channelLabel: CHANNEL_LABELS[st.channel] || st.channel,
        due: l.stall >= 4 ? `today · ${l.stall} days since contact` : l.stall > 0 ? 'today' : 'tomorrow',
        bucket: l.stall > 0 ? 1 : 2,
      };
    });
  // Hand-added tasks: open ones, plus those finished today (so ticking one doesn't make it vanish).
  const handTasks = s.leadTasks
    .filter((t) => !t.done || t.at === doneToday || (t.due && t.due >= today))
    .filter((t) => owner === 'Salesperson' || t.ownerId === owner)
    .sort((a, b) => (a.due || today).localeCompare(b.due || today))
    .flatMap<TodayTask>((t) => {
      const lead = leadById(s, t.leadId);
      if (!lead) return [];
      const dueIso = t.due || today;
      return [
        {
          id: t.id,
          leadId: t.leadId,
          title: t.title,
          company: lead.company,
          stageName: stagesFor(s, lead.segment).find((x) => x.id === t.stageId)?.name ?? stageOf(s, lead).name,
          channelLabel: CHANNEL_LABELS[t.channel] || t.channel,
          due: dueIso === today ? 'today' : isoLabel(dueIso),
          // Ticked off today, an overdue task stays in Overdue (crossed out) until tomorrow.
          bucket: dueIso < today ? 0 : dueIso === today ? 1 : 2,
          task: { done: t.done, owner: memberName(s, t.ownerId, t.ownerName), dueIso, overdue: isOverdue(t, today) },
        },
      ];
    });
  const tasks = [...handTasks, ...funnelTasks];
  const groups = [
    { label: 'Overdue', fg: '#B42318', tasks: tasks.filter((t) => t.bucket === 0) },
    { label: 'Today', fg: '#0F1B16', tasks: tasks.filter((t) => t.bucket === 1) },
    { label: 'Next up', fg: '#475750', tasks: tasks.filter((t) => t.bucket === 2) },
  ];

  return (
    <Screen title="Today">
      <FilterBar
        chips={[{ value: owner, options: ['Salesperson', ...salesPeople(s)], onChange: setOwner }]}
        dirty={owner !== 'Salesperson'}
        onClear={() => {
          setOwner('Salesperson');
        }}
      />
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
        {s.leads.length === 0 && (
          <EmptyState title="Nothing to do yet" text="Today fills itself from your deals: each deal's next step in the funnel, plus the tasks you add. Start with a deal." action={{ label: 'New deal', onClick: () => set({ newLeadOpen: true }) }} />
        )}
        <div style={{ fontSize: 13.5, color: 'var(--text-2)', lineHeight: 1.55, maxWidth: 640 }}>Tasks are generated by the funnel, and each one opens with the script for that stage. Tasks added with New task sit alongside them until they are done.</div>
        {groups.map((g) => (
          <div key={g.label} data-group={g.label} style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 9 }}>
              <span style={{ fontSize: 10.5, letterSpacing: '0.09em', textTransform: 'uppercase', color: g.fg }}>{g.label}</span>
              <span style={{ flex: 1, height: 1, background: 'var(--border)' }} />
              <span style={{ fontSize: 11, color: 'var(--text-2)' }}>{g.tasks.length === 1 ? '1 task' : g.tasks.length + ' tasks'}</span>
            </div>
            {g.tasks.map((t) => (
              <div key={t.id} data-task={t.task ? t.id : undefined} style={{ background: 'var(--white)', border: '1px solid var(--border)', borderRadius: 10, padding: '14px 15px', display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap' }}>
                {t.task && (
                  <button
                    type="button"
                    title={t.task.done ? 'Reopen' : 'Mark done'}
                    onClick={() => toggleLeadTask(t.id)}
                    style={{ flex: '0 0 19px', width: 19, height: 19, borderRadius: 6, border: `1px solid ${t.task.done ? '#14503C' : '#CAD3CE'}`, background: t.task.done ? '#14503C' : '#FFFFFF', color: '#FFFFFF', fontSize: 11, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 0 }}
                  >
                    {t.task.done ? '✓' : ''}
                  </button>
                )}
                <div style={{ flex: 1, minWidth: 200, display: 'flex', flexDirection: 'column', gap: 3 }}>
                  <span style={{ fontSize: 13.5, fontWeight: 600, color: t.task?.done ? '#93A39B' : undefined, textDecoration: t.task?.done ? 'line-through' : 'none' }}>{t.title}</span>
                  <span style={{ fontSize: 12, color: t.task?.overdue ? 'var(--danger)' : 'var(--text-2)' }}>
                    {t.company} · {t.stageName} · {t.task?.overdue ? 'overdue · was due' : 'due'} {t.due}
                    {t.task ? ' · ' + t.task.owner : ''}
                  </span>
                </div>
                <span style={{ fontSize: 11.5, fontWeight: 500, background: 'var(--ink)', color: 'var(--white)', padding: '4px 9px', borderRadius: 6, whiteSpace: 'nowrap' }}>{t.channelLabel}</span>
                {t.task && (
                  <button type="button" className="btn-outline" title="Edit this task" onClick={() => set({ taskOpen: true, taskEditId: t.id })}>
                    Edit
                  </button>
                )}
                <button type="button" className="btn-outline" onClick={() => openLead(t.leadId)}>
                  {t.task ? 'Open lead' : 'Open script'}
                </button>
              </div>
            ))}
          </div>
        ))}
      </div>
    </Screen>
  );
}
